"""Init database

Revision ID: 4e1b386067c0
Revises: 
Create Date: 2026-03-18 21:30:57.525706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1b386067c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_prices_id'), 'currency_prices', ['id'], unique=False)
    op.create_index(op.f('ix_currency_prices_ticker'), 'currency_prices', ['ticker'], unique=False)
    op.create_index(op.f('ix_currency_prices_timestamp'), 'currency_prices', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_prices_timestamp'), table_name='currency_prices')
    op.drop_index(op.f('ix_currency_prices_ticker'), table_name='currency_prices')
    op.drop_index(op.f('ix_currency_prices_id'), table_name='currency_prices')
    op.drop_table('currency_prices')
    # ### end Alembic commands ###
